/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as VipRouteImport } from './routes/vip'
import { Route as TrackRouteImport } from './routes/track'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WarrantyIndexRouteImport } from './routes/warranty.index'
import { Route as WarrantyVerifyRouteImport } from './routes/warranty.verify'
import { Route as WarrantyDashboardRouteImport } from './routes/warranty.dashboard'
import { Route as WarrantyCarsRouteImport } from './routes/warranty.cars'
import { Route as WarrantyAuthRouteImport } from './routes/warranty.auth'
import { Route as WarrantyAdminRouteImport } from './routes/warranty.admin'
import { Route as WarrantyActivateRouteImport } from './routes/warranty.activate'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as WarrantyCertificateIdRouteImport } from './routes/warranty.certificate.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyIndexRoute = WarrantyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WarrantyRoute,
} as any)
const WarrantyVerifyRoute = WarrantyVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => WarrantyRoute,
} as any)
const WarrantyDashboardRoute = WarrantyDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WarrantyRoute,
} as any)
const WarrantyCarsRoute = WarrantyCarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => WarrantyRoute,
} as any)
const WarrantyAuthRoute = WarrantyAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => WarrantyRoute,
} as any)
const WarrantyAdminRoute = WarrantyAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => WarrantyRoute,
} as any)
const WarrantyActivateRoute = WarrantyActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => WarrantyRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const WarrantyCertificateIdRoute = WarrantyCertificateIdRouteImport.update({
  id: '/certificate/$id',
  path: '/certificate/$id',
  getParentRoute: () => WarrantyRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/mcp': typeof McpRoute
  '/offers': typeof OffersRoute
  '/services': typeof ServicesRouteWithChildren
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/vip': typeof VipRoute
  '/warranty': typeof WarrantyRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/product/$id': typeof ProductIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/warranty/activate': typeof WarrantyActivateRoute
  '/warranty/admin': typeof WarrantyAdminRoute
  '/warranty/auth': typeof WarrantyAuthRoute
  '/warranty/cars': typeof WarrantyCarsRoute
  '/warranty/dashboard': typeof WarrantyDashboardRoute
  '/warranty/verify': typeof WarrantyVerifyRoute
  '/warranty/': typeof WarrantyIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/warranty/certificate/$id': typeof WarrantyCertificateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/mcp': typeof McpRoute
  '/offers': typeof OffersRoute
  '/services': typeof ServicesRouteWithChildren
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/vip': typeof VipRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/product/$id': typeof ProductIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/warranty/activate': typeof WarrantyActivateRoute
  '/warranty/admin': typeof WarrantyAdminRoute
  '/warranty/auth': typeof WarrantyAuthRoute
  '/warranty/cars': typeof WarrantyCarsRoute
  '/warranty/dashboard': typeof WarrantyDashboardRoute
  '/warranty/verify': typeof WarrantyVerifyRoute
  '/warranty': typeof WarrantyIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/warranty/certificate/$id': typeof WarrantyCertificateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/mcp': typeof McpRoute
  '/offers': typeof OffersRoute
  '/services': typeof ServicesRouteWithChildren
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/vip': typeof VipRoute
  '/warranty': typeof WarrantyRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/product/$id': typeof ProductIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/warranty/activate': typeof WarrantyActivateRoute
  '/warranty/admin': typeof WarrantyAdminRoute
  '/warranty/auth': typeof WarrantyAuthRoute
  '/warranty/cars': typeof WarrantyCarsRoute
  '/warranty/dashboard': typeof WarrantyDashboardRoute
  '/warranty/verify': typeof WarrantyVerifyRoute
  '/warranty/': typeof WarrantyIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/warranty/certificate/$id': typeof WarrantyCertificateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/mcp'
    | '/offers'
    | '/services'
    | '/shop'
    | '/sitemap.xml'
    | '/track'
    | '/vip'
    | '/warranty'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/product/$id'
    | '/services/$slug'
    | '/warranty/activate'
    | '/warranty/admin'
    | '/warranty/auth'
    | '/warranty/cars'
    | '/warranty/dashboard'
    | '/warranty/verify'
    | '/warranty/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/warranty/certificate/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/mcp'
    | '/offers'
    | '/services'
    | '/shop'
    | '/sitemap.xml'
    | '/track'
    | '/vip'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/product/$id'
    | '/services/$slug'
    | '/warranty/activate'
    | '/warranty/admin'
    | '/warranty/auth'
    | '/warranty/cars'
    | '/warranty/dashboard'
    | '/warranty/verify'
    | '/warranty'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/warranty/certificate/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/mcp'
    | '/offers'
    | '/services'
    | '/shop'
    | '/sitemap.xml'
    | '/track'
    | '/vip'
    | '/warranty'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/product/$id'
    | '/services/$slug'
    | '/warranty/activate'
    | '/warranty/admin'
    | '/warranty/auth'
    | '/warranty/cars'
    | '/warranty/dashboard'
    | '/warranty/verify'
    | '/warranty/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/warranty/certificate/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  McpRoute: typeof McpRoute
  OffersRoute: typeof OffersRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrackRoute: typeof TrackRoute
  VipRoute: typeof VipRoute
  WarrantyRoute: typeof WarrantyRouteWithChildren
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ProductIdRoute: typeof ProductIdRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty/': {
      id: '/warranty/'
      path: '/'
      fullPath: '/warranty/'
      preLoaderRoute: typeof WarrantyIndexRouteImport
      parentRoute: typeof WarrantyRoute
    }
    '/warranty/verify': {
      id: '/warranty/verify'
      path: '/verify'
      fullPath: '/warranty/verify'
      preLoaderRoute: typeof WarrantyVerifyRouteImport
      parentRoute: typeof WarrantyRoute
    }
    '/warranty/dashboard': {
      id: '/warranty/dashboard'
      path: '/dashboard'
      fullPath: '/warranty/dashboard'
      preLoaderRoute: typeof WarrantyDashboardRouteImport
      parentRoute: typeof WarrantyRoute
    }
    '/warranty/cars': {
      id: '/warranty/cars'
      path: '/cars'
      fullPath: '/warranty/cars'
      preLoaderRoute: typeof WarrantyCarsRouteImport
      parentRoute: typeof WarrantyRoute
    }
    '/warranty/auth': {
      id: '/warranty/auth'
      path: '/auth'
      fullPath: '/warranty/auth'
      preLoaderRoute: typeof WarrantyAuthRouteImport
      parentRoute: typeof WarrantyRoute
    }
    '/warranty/admin': {
      id: '/warranty/admin'
      path: '/admin'
      fullPath: '/warranty/admin'
      preLoaderRoute: typeof WarrantyAdminRouteImport
      parentRoute: typeof WarrantyRoute
    }
    '/warranty/activate': {
      id: '/warranty/activate'
      path: '/activate'
      fullPath: '/warranty/activate'
      preLoaderRoute: typeof WarrantyActivateRouteImport
      parentRoute: typeof WarrantyRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty/certificate/$id': {
      id: '/warranty/certificate/$id'
      path: '/certificate/$id'
      fullPath: '/warranty/certificate/$id'
      preLoaderRoute: typeof WarrantyCertificateIdRouteImport
      parentRoute: typeof WarrantyRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface WarrantyRouteChildren {
  WarrantyActivateRoute: typeof WarrantyActivateRoute
  WarrantyAdminRoute: typeof WarrantyAdminRoute
  WarrantyAuthRoute: typeof WarrantyAuthRoute
  WarrantyCarsRoute: typeof WarrantyCarsRoute
  WarrantyDashboardRoute: typeof WarrantyDashboardRoute
  WarrantyVerifyRoute: typeof WarrantyVerifyRoute
  WarrantyIndexRoute: typeof WarrantyIndexRoute
  WarrantyCertificateIdRoute: typeof WarrantyCertificateIdRoute
}

const WarrantyRouteChildren: WarrantyRouteChildren = {
  WarrantyActivateRoute: WarrantyActivateRoute,
  WarrantyAdminRoute: WarrantyAdminRoute,
  WarrantyAuthRoute: WarrantyAuthRoute,
  WarrantyCarsRoute: WarrantyCarsRoute,
  WarrantyDashboardRoute: WarrantyDashboardRoute,
  WarrantyVerifyRoute: WarrantyVerifyRoute,
  WarrantyIndexRoute: WarrantyIndexRoute,
  WarrantyCertificateIdRoute: WarrantyCertificateIdRoute,
}

const WarrantyRouteWithChildren = WarrantyRoute._addFileChildren(
  WarrantyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  McpRoute: McpRoute,
  OffersRoute: OffersRoute,
  ServicesRoute: ServicesRouteWithChildren,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrackRoute: TrackRoute,
  VipRoute: VipRoute,
  WarrantyRoute: WarrantyRouteWithChildren,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ProductIdRoute: ProductIdRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
